package com.hosseinkurd.app.persianweekcalendar

import android.os.Bundle
import android.os.Handler
import android.os.Looper
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.hosseinkurd.component.persianweekcalendar.WorkCalendarView
import com.hosseinkurd.component.persianweekcalendar.interfaces.OnClickListenerPersianCalendarLibrary
import com.hosseinkurd.component.persianweekcalendar.models.CalendarDayModel
import com.hosseinkurd.component.persianweekcalendar.models.WorkCalendarModel


class MainActivity : AppCompatActivity() {

    private lateinit var workCalendarView: WorkCalendarView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        workCalendarView = findViewById(R.id.workCalendarView)
        initInterface()
        // call if autoGenerateDays if 'autoGenerateDays' is false
        // addItemsToCalendar()
        Handler(Looper.getMainLooper()).postDelayed({
            workCalendarView.onClickListenerPersianCalendarLibrary?.onPersianCalendarLibraryScrolled(
                firstWorkCalendarModel = workCalendarView.getFirstDayOfWeek(),
                lastWorkCalendarModel = workCalendarView.getLastDayOfWeek()
            )
        }, 600)
        /*val itemWidth = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            val windowMetrics: WindowMetrics =
                windowManager.currentWindowMetrics
            val insets = windowMetrics.windowInsets
                .getInsetsIgnoringVisibility(WindowInsets.Type.systemBars())
            windowMetrics.bounds.width() - insets.left - insets.right
        } else {
            val displayMetrics = DisplayMetrics()
            windowManager.defaultDisplay.getMetrics(displayMetrics)
            displayMetrics.widthPixels
        }*/
    }

    private fun initInterface() {
        findViewById<Button>(R.id.buttonGoToToday).setOnClickListener {
            workCalendarView.showTodayTasks()
        }
        findViewById<Button>(R.id.buttonGoToSelected).setOnClickListener {
            workCalendarView.showSelectedDayTasks()
        }
        findViewById<Button>(R.id.buttonFirstDayInView).setOnClickListener {
            Toast.makeText(
                this,
                "First Day In View : '${workCalendarView.getFirstDayOfWeek()?.persianDate}'",
                Toast.LENGTH_LONG
            ).show()
        }
        findViewById<Button>(R.id.buttonLastDayInView).setOnClickListener {
            Toast.makeText(
                this,
                "Last Day In View : '${workCalendarView.getLastDayOfWeek()?.persianDate}'",
                Toast.LENGTH_LONG
            ).show()
        }
        findViewById<Button>(R.id.buttonNextWeek).setOnClickListener {
            println("buttonNextWeek ...")
            workCalendarView.showNextWeek()
        }
        findViewById<Button>(R.id.buttonPastWeek).setOnClickListener {
            println("buttonPastWeek ...")
            workCalendarView.showPastWeek()
        }
        workCalendarView.onClickListenerPersianCalendarLibrary =
            object : OnClickListenerPersianCalendarLibrary {
                override fun onPersianCalendarLibraryStartClicked() {

                }

                override fun onPersianCalendarLibraryEndClicked() {

                }

                override fun onPersianCalendarLibraryClicked(
                    workCalendarModel: WorkCalendarModel
                ) {
                    workCalendarView.changeSelectedItem(workCalendarModel)
                }

                override fun onPersianCalendarLibraryScrolled(
                    firstWorkCalendarModel: WorkCalendarModel?,
                    lastWorkCalendarModel: WorkCalendarModel?
                ) {
                    println("onPersianCalendarLibraryScrolled >> firstWorkCalendarModel : $firstWorkCalendarModel")
                    println("onPersianCalendarLibraryScrolled >> lastWorkCalendarModel : $lastWorkCalendarModel")
                    println("onPersianCalendarLibraryScrolled >> MoreNumerousMonthInWeek : ${workCalendarView.getMoreNumerousMonthInWeek()}")
                    println("onPersianCalendarLibraryScrolled >> *************************************************")
                    workCalendarView.setTitle(workCalendarView.getMoreNumerousMonthInWeek())
                }

            }
    }

    private fun addItemsToCalendar() {
        workCalendarView.addItems(isoList = mutableListOf<CalendarDayModel>().apply { addAll(items) })
        workCalendarView.showSelectedDayTasks()
    }

    private val items = mutableListOf<CalendarDayModel>().apply {
        add(CalendarDayModel(isoDate = "2021-11-01"))
        add(CalendarDayModel(isoDate = "2021-11-02"))
        add(CalendarDayModel(isoDate = "2021-11-03"))
        add(CalendarDayModel(isoDate = "2021-11-04"))
        add(CalendarDayModel(isoDate = "2021-11-05"))
        add(CalendarDayModel(isoDate = "2021-11-06"))
        add(CalendarDayModel(isoDate = "2021-11-07"))
        add(CalendarDayModel(isoDate = "2021-11-08"))
        add(CalendarDayModel(isoDate = "2021-11-09"))
        add(CalendarDayModel(isoDate = "2021-11-10"))
        add(CalendarDayModel(isoDate = "2021-11-11"))
        add(CalendarDayModel(isoDate = "2021-11-12"))
        add(CalendarDayModel(isoDate = "2021-11-13"))
        add(CalendarDayModel(isoDate = "2021-11-14"))
        add(CalendarDayModel(isoDate = "2021-11-15"))
        add(CalendarDayModel(isoDate = "2021-11-16"))
        add(CalendarDayModel(isoDate = "2021-11-17"))
        add(CalendarDayModel(isoDate = "2021-11-18"))
        add(CalendarDayModel(isoDate = "2021-11-19"))
        add(CalendarDayModel(isoDate = "2021-11-20"))
        add(CalendarDayModel(isoDate = "2021-11-21"))
        add(CalendarDayModel(isoDate = "2021-11-22"))
        add(CalendarDayModel(isoDate = "2021-11-23"))
        add(CalendarDayModel(isoDate = "2021-11-24"))
        add(CalendarDayModel(isoDate = "2021-11-25"))
        add(CalendarDayModel(isoDate = "2021-11-26"))
        add(CalendarDayModel(isoDate = "2021-11-27"))
        add(CalendarDayModel(isoDate = "2021-11-28"))
        add(CalendarDayModel(isoDate = "2021-11-29"))
        add(CalendarDayModel(isoDate = "2021-11-30"))
        add(CalendarDayModel(isoDate = "2021-12-01"))
        add(CalendarDayModel(isoDate = "2021-12-02"))
        add(CalendarDayModel(isoDate = "2021-12-03"))
        add(CalendarDayModel(isoDate = "2021-12-04"))
        add(CalendarDayModel(isoDate = "2021-12-05"))
        add(CalendarDayModel(isoDate = "2021-12-06"))
        add(CalendarDayModel(isoDate = "2021-12-07"))
        add(CalendarDayModel(isoDate = "2021-12-08"))
        add(CalendarDayModel(isoDate = "2021-12-09"))
        add(CalendarDayModel(isoDate = "2021-12-10"))
        add(CalendarDayModel(isoDate = "2021-12-11"))
        add(CalendarDayModel(isoDate = "2021-12-12"))
        add(CalendarDayModel(isoDate = "2021-12-13"))
        add(CalendarDayModel(isoDate = "2021-12-14"))
        add(CalendarDayModel(isoDate = "2021-12-15"))
        add(CalendarDayModel(isoDate = "2021-12-16"))
        add(CalendarDayModel(isoDate = "2021-12-17"))
        add(CalendarDayModel(isoDate = "2021-12-18"))
        add(CalendarDayModel(isoDate = "2021-12-19"))
        add(CalendarDayModel(isoDate = "2021-12-20"))
        add(CalendarDayModel(isoDate = "2021-12-21"))
        add(CalendarDayModel(isoDate = "2021-12-22"))
        add(CalendarDayModel(isoDate = "2021-12-23"))
        add(CalendarDayModel(isoDate = "2021-12-24"))
        add(CalendarDayModel(isoDate = "2021-12-25"))
        add(CalendarDayModel(isoDate = "2021-12-26"))
        add(CalendarDayModel(isoDate = "2021-12-27"))
        add(CalendarDayModel(isoDate = "2021-12-28"))
        add(CalendarDayModel(isoDate = "2021-12-29"))
        add(CalendarDayModel(isoDate = "2021-12-30"))
    }

}